services:
  postgres:
    image: postgres:17.2-bookworm
    environment:
      POSTGRES_USER: boilerplate_user
      POSTGRES_PASSWORD: boilerplate_password
      POSTGRES_DB: boilerplate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.1.1-bookworm
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
      - ./valkey.conf:/etc/valkey.conf
    command: ["valkey-server", "/etc/valkey.conf"]

volumes:
  postgres_data:
  valkey_data:
