// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, db DBTX, name string) (int32, error)
	GetItem(ctx context.Context, db DBTX, id int32) (Item, error)
	GetItemsPaginated(ctx context.Context, db DBTX, lastItemID int32, pageSize int32) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
