# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Golangci-lint
    # You may pin to the exact commit or the version.
    # uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: v1.62.2
        install-mode: goinstall
        working-directory: .
        github-token: ${{ github.token }}
        only-new-issues: false
        skip-cache: false
        skip-save-cache: false
        problem-matchers: false
        cache-invalidation-interval: 7
